services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - beacon-network

  temporal:
    image: temporalio/auto-setup:latest
    ports:
      - "7233:7233"
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=${TEMPORAL_POSTGRES_USER}
      - POSTGRES_PWD=${TEMPORAL_POSTGRES_PASSWORD}
      - POSTGRES_SEEDS=temporal-postgres
    depends_on:
      - temporal-postgres
    networks:
      - beacon-network

  temporal-postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${TEMPORAL_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEMPORAL_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEMPORAL_POSTGRES_DB}
    volumes:
      - temporal_postgres_data:/var/lib/postgresql/data
    networks:
      - beacon-network

  temporal-ui:
    image: temporalio/ui:latest
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - temporal
    networks:
      - beacon-network

  beacon-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      DATABASE_URL: ${DOCKER_DATABASE_URL}
      TEMPORAL_HOST: "temporal:7233"
    depends_on:
      - postgres
      - temporal
    restart: unless-stopped
    networks:
      - beacon-network

volumes:
  postgres_data:
  temporal_postgres_data:

networks:
  beacon-network:
    driver: bridge